require:
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - Gemfile
    - Rakefile
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
    - spec/fixtures/**/*
    - tmp/**/*
    - ".git/**/*"
    - bin/*
    - db/migrate/*.rb
    - config/application.rb
  TargetRubyVersion: 3.0.2
  SuggestExtensions: false

Rails:
  Enabled: true

Layout/LineLength:
  Max: 170

Lint/DuplicateRequire:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb

Metrics/MethodLength:
  Max: 15

Rails/AfterCommitOverride:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/EagerEvaluationLogMessage:
  Exclude:
    - db/seeds.rb
    - db/fixtures/*.rb

Rails/Output:
  Exclude:
    - db/seeds.rb
    - db/fixtures/*.rb

Style/CombinableLoops:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/KeywordParametersOrder:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
