version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUNDLE_WITHOUT="${BUNDLE_WITHOUT}"
        - BUNDLER_VERSION=2.2.32
        - FOLDERS_TO_REMOVE=""
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      - RAILS_ENV=development
      - JWT_SECRET_TOKEN
      - PASSWORD_RECOVERY_LINK_TEMPLATE
    entrypoint: ./bin/entrypoints/docker-entrypoint $RAILS_ENV

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - database
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./bin/entrypoints/sidekiq-entrypoint

volumes:
  gem_cache:
  db_data:
