version: '3.4'

x-app: &app_base
  image: ${IMAGE_NAME}
  environment:
    - RAILS_ENV=development
    - JWT_SECRET_TOKEN

  build:
    context: .
    dockerfile: Dockerfile
    args:
      - BUNDLE_WITHOUT="${BUNDLE_WITHOUT}"
      - BUNDLER_VERSION=2.3.10
      - FOLDERS_TO_REMOVE=""

  depends_on:
    - database
    - elasticsearch
    - redis

  links:
    - database
    - elasticsearch
  volumes:
    - ruby_bundle:/usr/local/bundle

services:
  app:
    <<: *app_base
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
    env_file: .env.docker
    environment:
      - JWT_SECRET_TOKEN
      - PASSWORD_RECOVERY_LINK_TEMPLATE
      - MAILER_SENDER_ADDRESS
    entrypoint: ./bin/entrypoints/docker-entrypoint $RAILS_ENV

  nginx:
    restart: unless-stopped
    build:
      context: ./docker
      dockerfile: nginx.Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"

  database:
    image: postgres:12.1
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./bin/docker-init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2.6
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    sysctls:
      - net.core.somaxconn=511

  sidekiq:
    <<: *app_base
    depends_on:
      - app
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
    env_file: .env.docker
    environment:
      - REDIS_URL=redis://redis:6379/1
    entrypoint: ./bin/entrypoints/sidekiq-entrypoint

  elasticsearch:
    image: elasticsearch:8.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
      - http.cors.allow-origin="/.*/"
      - http.cors.enabled=true
    env_file: .env.docker
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  ruby_bundle:
  db_data:
  redis:
  elasticsearch:
