version: '3.4'

x-app: &app_base
  image: ${IMAGE_NAME}
  environment:
    - RAILS_ENV=development
    - JWT_SECRET_TOKEN

  build:
    context: .
    dockerfile: Dockerfile
    args:
      - BUNDLE_WITHOUT="${BUNDLE_WITHOUT}"
      - BUNDLER_VERSION=2.2.32
      - FOLDERS_TO_REMOVE=""

  depends_on:
    - database
    - redis

  links:
    - database
  volumes:
    - gem_cache:/usr/local/bundle/gems

services:
  app:
    <<: *app_base
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - ./docker/database.yml:/app/config/database.yml
    env_file: .env
    environment:
      - JWT_SECRET_TOKEN
      - PASSWORD_RECOVERY_LINK_TEMPLATE
      - MAILER_SENDER_ADDRESS
    entrypoint: ./bin/entrypoints/docker-entrypoint $RAILS_ENV

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./bin/docker-init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2.6
    sysctls:
      - net.core.somaxconn=511

  sidekiq:
    <<: *app_base
    depends_on:
      - app
      - database
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./bin/entrypoints/sidekiq-entrypoint

volumes:
  gem_cache:
  db_data:
