inherit_from: ../.rubocop.yml

Layout/SpaceBeforeBrackets:
  Enabled: false

RSpec/VariableName:
  Enabled: false

Metrics/BlockLength:
  Max: 500

RSpec/ScatteredSetup:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

Lint/ConstantDefinitionInBlock:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false
