default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  min_messages: warning

development:
  <<: *default
  database: tollowy_development

test:
  <<: *default
  database: tollowy_test

production:
  <<: *default
  database: <%= ENV["DATABASE_PRODUCTION_DB"] %>>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
