default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tollowy_development

test:
  <<: *default
  database: tollowy_test

production:
  <<: *default
  database: <%= ENV["DATABASE_PRODUCTION_DB"] || 'tollowy_production' %>
