name: Tests and Quality
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-verison: [3.0.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-verison }}
          bundler-cache: true

      - name: Run linters and security checks
        run: bin/quality

  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-verison: [ 3.0.2 ]

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tollowy_test
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-verison }}
          bundler-cache: true

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build and test with Rake
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
          DATABASE_PASSWORD: postgres
        run: |
          bin/bundle exec rake db:test:prepare

      - name: Run tests
        run: bin/tests
